import Head from 'next/head'
import React from 'react'
import Header1 from '../components/Header'
import Carousel, { Dots } from '@brainhubeu/react-carousel'
import Plyr from 'plyr-react'
import 'plyr-react/dist/plyr.css'
import Footer1 from '../components/Footer1'
import ProgramasRecolocacion1 from '../components/ProgramasRecolocacion'

// SVG
import LogoRecolocate_svg from '@svg/logo_recolocate.svg'
import LogoRecolocate2_svg from '@svg/logo_recolocate2.svg'
import infografia8_svg from '@svg/infografia8_1.svg'
import recolocate11m_svg from '@svg/recolocate12m.svg'
import recolocate13_svg from '@svg/recolocate13.svg'
import recolocate14_svg from '@svg/recolocate14.svg'
import triangle3_svg from '@svg/triangle3.svg'
import esquina5_svg from '@svg/esquina5.svg'
import esquina6_svg from '@svg/esquina6.svg'
import telegram_svg from '@svg/telegram.svg'
import mensajeEnviado_svg from '@svg/mensaje_enviado.svg'
import recolocatefondo5_svg from '@svg/recolocatefondo5.svg'
import infografia10v_svg from '@svg/infografia10v.svg'

import ImageSVG from 'shared/Images'
import BgParallax from 'shared/Parallax'
import ContactoForm from '@components/ContactoForm'

export default class Home extends React.PureComponent<any,any> {
  
  constructor(props){
    super(props)
    // console.log('home props::',props.router.pathname)
    this.state = { showCarrousel: false, carruselValue: 0 }
    this.changeCarrousel = this.changeCarrousel.bind(this)
  }

  componentDidMount(){
    setTimeout(()=> { this.setState({ showCarrousel: true })},1000)
  }

  changeCarrousel(carruselValue){
    console.log('cambiando valor::',carruselValue)
    this.setState({ carruselValue: carruselValue });
  }

  render(){
    const state = this.state
    console.log('home props::',this.props,this.props.router)

  return <>
    <Head>
      <title>RECOLÓCATE | Job & Career Coaching</title>
      <meta name="description" content="Generated by create next app" />
    </Head>
    <Header1 />
    {/* Imagen Principal */}
    <BgParallax className="w100 fondo1 _desk" id="inicio-1"
      imageSrc="images/handshake7.jpg"
    >
      <div className="s1 inline-h">INNOVACIÓN TECNOLÓGICA Y MTEODOLÓGICA EN PROGRAMAS DE OUTPLACEMENT</div>
      <div className="s2">
        Somos expertos en prepararte y guiarte durante tu transición de carrera, respaldados por un equipo profesional con alta experiencia, un enfoque de procesos innovador y una atención personalizada, integrando herramientas tecnológicas y profesionales únicas en el mercado.
      </div>
    </BgParallax>
    <div id="inicio-2" className="_mobile m-fondo1 inline-v jc" style={{ backgroundImage: "url('images/handshake8.jpg')" }} >
      <div className="sec1">
        <ImageSVG svgRaw={LogoRecolocate_svg} className="logo"/>  
        <span>Somos expertos en prepararte y guiarte durante tu transición de carrera, respaldados por un equipo profesional con alta experiencia, un enfoque de procesos innovador y una atención personalizada.</span> 
    </div>
    </div>
    {/* 2) Quienes somos  */}
  <div id="nosotros-1" className="main-div _desk w100">
    <div className="title1">QUIÉNES SOMOS</div>
    <div className="c1">
      <div>
        <ImageSVG svgRaw={LogoRecolocate2_svg} className="r-logo"/>        
      </div>
      <div className="somos">
      <span>Somos RECOLOCATE - Job & Career Coaching, firma peruana especializada en Programas de Recolocación Laboral (Outplacement) y Desarrollo Profesional. <br/>
        Lideramos el mercado peruano con un conjunto de mejoras a los Programas Tradicionales de Outplacemente en donde introdujimos innovación metodológica y tecnológica, lo que nos permite adaptarnos a diversos escenarios y garantizar la efectividad de nuestros procesos aplicados.
      </span>
      </div>
    </div> 
  </div>
  <div id="nosotros-2" 
    className="m-somos inline-v jc-center _mobile w100">
    <div className="ctn4 inline-v">
      <div style={{ padding: '0.9vh 15vw' }} 
        className="title6 mB02"><h2>NOSOTROS</h2></div>
      <div>Somos RECOLOCATE - Job & Career Coaching, firma peruana especialista en Programas de Outplacement y Desarrollo Profesional. 
          Lideramos el mercado peruano, en innovación metodológica y tecnológica, lo que nos permite adaptarnos a diversos escenarios y garantizar la efectividad de nuestros procesos aplicados. </div>
    </div>
    <img src="images/mt-job2.png"/>
  </div>
  {/* Presentacion */}
  <div className="inline-v jc-center presentacion w100">
    <img className="v1" src="images/vector2.png" alt=""/>
    <img className="v2" src="images/vector4.png" alt=""/>
    <div className="title5 mB02">
      <span>PRESENTACIÓN</span>
    </div>
    <div className="youtube">
      <Plyr source={
          {
            type: 'video',
            sources: [
              { src: "https://storage.googleapis.com/unicore1/video_recolocate.mp4" }
            ],
            poster: "images/video1.jpg"
          }
        }
        options={{  }}
      />
    </div>
  </div>
  <div className="palabras inline-v jc-center w100">
    <div className="circle6"></div>
    <div className="title11 inline-h mB03">
      <span>PALABRAS DEL DIRECTOR</span>
    </div>
    <div style={{ zIndex: 10 }} className="inline-h m-reverse">
      <div style={{ backgroundImage: "url(images/franco_circle2.jpg)" }}
        className="img1 inline-h cover-c">
      </div>
      <div className="inline-v text5 tx2 mb2 mT01">
        <span>En los últimos años hemos estado dedicados al esfuerzo, gratificante, de acompañar y facilitar directamente a los profesionales en la difícil coyuntura de Transición de Carrera.</span>
        <span>Hemos desarrollado una solución más efectiva y diferenciada al Outplacement tradicional. Decidimos atender el mercado corporativo (empresas) y también directamente a los profesionales, con la seguridad de constituirnos en una solución a los problemas que surgen de los procesos de desvinculación laboral, tanto individuales como grupales.</span>
        <span>Nuestras soluciones cuentan con la constribución de diferentes perspectivas funcionales y disciplinas, como Neurociencias, que aportan decisivamente en la elaboración de los Programas de Outplacement formando un producto valioso y único, orientado tanto a cubrir las necesidades del profesional como los objetivos de la organización contratante.</span>
      </div>
    </div>
  </div>
  {/* Servicios */}
  <div className="title2">SERVICIOS</div>
  {/* Outplacement */}
  <div style={{ backgroundImage: "url('images/reunion4.jpg')" }} className="inline-h col2 _desk" id="outplacement">
    <div></div>
    <div className="c2">
      <div className="mB02 c ls1"> <h2>PROGRAMAS DE RECOLOCACIÓN LABORAL <br/> - OUTPLACEMENT </h2> </div>
      <div className="mB03"><span> Somos expertos en Programas de Recolocación   Laboral (Outplacement) enfocados en garantizar la efectividad de nuestro proceso, diseñado para reducir el tiempo y/o mejorar la calidad de empleo durante la vinculación con el mercado.</span></div>
      <div className="mB08"><span>El éxito de nuestro proceso se basa en la constante innovación metodológica y tecnológica aplicada durante las etapas de desarrollo, las cuales son acompañadas por especialistas certificados.</span></div>
    </div>
  </div>

  <div className="m-outplacement inline-v jc-center _mobile w100" 
    style={{ backgroundImage: "url(images/equipo4.jpg)" }}>
    <div className="ctn4 inline-v">
      <div style={{ padding: "0.9vh 2vw" }}
      className="title6 mB02 ls1">
        <h3>PROGRAMAS DE RECOLOCACIÓN LABORAL</h3>
      </div>
      <div>Somos RECOLOCATE - Job & Career Coaching, firma peruana especialista en Programas de Outplacement y Desarrollo Profesional. 
          Lideramos el mercado peruano, en innovación metodológica y tecnológica, lo que nos permite adaptarnos a diversos escenarios y garantizar la efectividad de nuestros procesos aplicados. </div>
    </div>
  </div>
  {/* Programas de Recolocación */}
  <ProgramasRecolocacion1 />

  {/* Capacidades de empleabilidad  */}
  <div className="inline-v capacidades _desk">
    <div className="wrap1 inline-v">
      <h2 className="mB03 ls2 c">DESARROLLO DEL PROGRAMA EN BASE A <br/> CAPACIDADES DE EMPLEABILIDAD</h2>
      <span className="mB03 c">La potente metodología de nuestros programas de transición de carrera permite el desarrollo (cierre de brechas) de CAPACIDADES DE EMPLEABILIDAD: Conocimiento de uno mismo, Marca Personal, Networking y Visibilidad.</span>
    </div>
  </div>
  <div className="sec2 _desk">
    <div className="col-2 w100 enfoque-pro inline-v">
      <div className="wrap1 inline-v">
        <h2 className="mB03 c">ENFOQUE DE PROCESOS</h2>
        <span className="mB03">Nuestros programas se basan en 4 procesos que integrados brindan un alcance holístico y metodológico de la recolocación laboral. Las herramientas, sesiones y talleres están alineados a dichos procesos para identificar oportunamente los puntos de mejora y aumentar las posibilidades de éxito.</span>
        <img src="images/herramientas3.png" alt="enfoque de procesos"/>
      </div>
    </div>
    <div id="infografia1" className="mitad2">
      <ImageSVG svgRaw={infografia8_svg} alt="outplacement recolocate"/>
    </div>
  </div>
  <div className="m-capacidades inline-v jc-center _mobile">
    <h2 className="mB03">DESARROLLA TUS CAPACIDADES DE EMPLEABILIDAD</h2>
    <span className="mB03">La potente metodología de nuestros programas de transición de carrera permite el desarrollo de capacidades de networking, comunicación efectiva y posicionamiento en el mercado laboral.</span>
    <span className="mB03">Basado en tu diagnóstico personal, nuestro staff de expertos se enfocará en reforzar los puntos críticos, mejorar tu perfil profesional y brindarte las herramientas necesarias para dominar el proceso de selección.</span>
  </div>
  <div className="m-infografia inline-v _mobile">
    <ImageSVG svgRaw={infografia10v_svg} alt="outplacement recolocate"/>
  </div>

  {/* Testimonios */}
  <div id="testimonios1" className="testimonios inline-v jc" 
    style={{ display: 'none'}}>
    <div className="title4 h1 mB03">TESTIMONIOS</div>
    <div className="unislider_ctn light">
      <div className="testimonios1 s1 glide">
        <div className="glide__track w100" data-glide-el="track">
          <ul id="li-publicaciones" className="glide__slides w100">
            <li>
              <div className="card4 inline-v">
                <img src="images/imagen1.jpg"/>
                <div className="h3">Manuel Moncada</div>
                <span>JEFE DE INGRESOS Y COSTOS</span>
                <span className="tt">"Mi paso por Recolócate ha sido una experiencia muy enriquecedora que me permitió autoevaluarme y explotar al máximo mis fortalezas y oportunidades en el proceso de transición Profesional. Gracias a la expertise que Recolócate posee y al entrenamiento recibido me ha sido posible aprovechar de una manera más eficiente mis postulaciones."</span>
              </div>
            </li>
            <li>
              <div className="card4 inline-v">
                <img src="images/imagen1.jpg"/>
                <div className="h3">Fernando Chung</div>
                <span>JEFE DE INGRESOS Y COSTOS</span>
                <span className="tt">En mi primera experiencia gerencial el acompañamiento de Recolócate me ha permitido enfrentar este nuevo desafío de una manera más segura y efectiva. Estoy trabajando en aspectos fundamentales para mi crecimiento profesional, como conducción de equipos de liderazgo a la par de recibir asesoría para resolver asuntos críticos asociado a la gestión de personas.</span>
              </div>
            </li>
            <li>            
              <div className="card4 inline-v">
                <img src="images/imagen1.jpg"/>
                <div className="h3">Enrique Caceres Cerro</div>
                <span>GERENTE GENERAL</span>
                <span className="tt">Recolocate es una muy innovadora forma de obtener la posicion laboral que uno busca y la remuneracion que uno realmente merece, lo recomiendo es un excelente sistema de busqueda de empleo.</span>
              </div>
            </li>
            <li>            
              <div className="card4 inline-v">
                <img src="images/persona1.jpg"/>
                <div className="h3">Gabriela López Prueba</div>
                <span>GERENTA DE VENTAS</span>
                <span className="tt">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tempore. Magnam minus praesentium quasi perferendis eligendi esse architecto labore soluta voluptate blanditiis id atque suscipit ipsam totam, nihil nulla obcaecati.</span>
              </div>
            </li>
            <li>            
              <div className="card4 inline-v">
                <img src="images/persona1.jpg"/>
                <div className="h3">Gabriela López Prueba</div>
                <span>GERENTA DE VENTAS</span>
                <span className="tt">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Quasi, tempore. Magnam minus praesentium quasi perferendis eligendi esse architecto labore soluta voluptate blanditiis id atque suscipit ipsam totam, nihil nulla obcaecati.</span>
              </div>
            </li>
          </ul>
        </div>
        <div className="glide__arrows" data-glide-el="controls">
          <button className="glide__arrow glide__arrow--left" data-glide-dir="<">{"<"}</button>
          <button className="glide__arrow glide__arrow--right" data-glide-dir=">">{">"}</button>
        </div>
        <div className="glide__bullets" data-glide-el="controls[nav]">
          <button className="glide__bullet" data-glide-dir="=0"></button>
          <button className="glide__bullet" data-glide-dir="=1"></button>
          <button className="glide__bullet" data-glide-dir="=2"></button>
          <button className="glide__bullet" data-glide-dir="=3"></button>
          <button className="glide__bullet" data-glide-dir="=4"></button>
        </div>
      </div>
    </div>
  </div>  
  
  {/* Enfoque de procesos */}
  <div id="proceso1" className="fondo4 inline-v w100">
      <h2 className="mB02">ETAPAS Y OBJETIVOS DEL PROGRAMA</h2>
      <span className="mw-100vh">Nuestros programas integran una serie de herramientas y objetivos acorde a nuestro enfoque de procesos para guiarte de forma ordenada en cada etapa, asegurando una recolocación exitosa.</span>
  </div>
  <div className="fondo5 _desk">   
    <ImageSVG svgRaw={recolocate11m_svg} alt=""/>
  </div>
  <div className="fondo9 inline-v _mobile">
    <ImageSVG svgRaw={recolocate13_svg} alt=""/>
    <ImageSVG style={{marginTop: '-11vw'}} svgRaw={recolocate14_svg} alt=""/>
  </div>
  <div className="elegirnos w100">
    <div className="T1 c-white">¿POR QUÉ ELEGIRNOS?</div>
    <div className="motivos">
      <div>
        <div className="circle1">
          <img src="images/experiencia3.jpg"/>
        </div>
        <span className="sub1">ALTA EXPERIENCIA <br/> Y EXPERTISSE</span>
        <div className="c4">En procesos específicos de Recolocación Laboral y en los demás procesos de Recursos Humanos. Poseemos años de experiencia en programas de recolocación.</div>
      </div>
      <div>
        <div className="circle1">
          <img src="images/atencion1.jpg"/>
        </div>
        <span className="sub1">ATENCIÓN <br/> PERSONALIZADA</span>
        <div className="c4">Que permite el acompañamiento conveniente para el logro del objetivo. Identificamos los puntos clave a desarrollar según las virtudes y falencias de cada profesional.</div>
      </div>
      <div>
        <div className="circle1">
          <img src="images/ventas5.jpg"/>
        </div>
        <span className="sub1">PROGRAMA <br/> INNOVADOR</span>
        <div className="c4">Con un enfoque de procesos que integra el uso de recursos y herramientas innovadoras, desarrollamos las capacidades de empleabilidad necesarias a fin de dominar el proceso de selección.</div>
      </div>
      <div>
        <div className="circle1">
            <img src="images/ahorro2.jpg"/>
        </div>
        <span className="sub1">PRECIOS <br/> COMPETITIVOS</span>
        <div className="c4">Nuestra metodología y organización sobre la cual trabajamos permite ofrecer los precios más competitivos dentro de la oferta seria de Programas de Recolocación Laboral.</div>
      </div>
    </div>
  </div>
  {/* CONSULTORIA EN PROGRAMAS DE RETIRO */}
  <BgParallax className="_desk consultoria1" 
    imageSrc="images/ejecutivos2.jpg" innerCss="col2 inline-h"
  >
    <ImageSVG svgRaw={triangle3_svg} alt="" className="triangle"/>
    <div className="w50"></div>
    <div style={{ zIndex: 15 }} className="class">
      <div className="T1 txs c mb-16 bold"><h2>CONSULTORÍA DE <br/>PROGRAMAS DE RETIRO</h2>
      </div>
      <div className="mB03"><span className="h3 wc1">Ofrecemos el acompañamiento continuo previo, durante y después de la ejecución del Plan de Retiro.</span></div>
      <div className="mB04"><span className="h3 wc1">Realizamos un diagnostico de la coyuntura, la evaluación del plan de acción, asesoría para la comunicación, entrenamiento para voceros, talleres de sensibilización, revisión de los instrumentos legales laborales, entre otros.</span></div>
    </div>
  </BgParallax>
  <div className="m-consultoria inline-v _mobile w100" 
    style={{ backgroundImage: 'url(images/programas-retiro2.jpg)' }}>
    <div className="ctn4 inline-v">
      <h2>CONSULTORÍA EN <br/> PROGRAMAS DE RETIRO</h2>
      <div className="tx2 mT02">
        <span>Ofrecemos el acompañamiento continuo previo, durante y después de la ejecución del Plan de Retiro.</span> 
        <span>Realizamos un diagnostico de la coyuntura, la evaluación del plan de acción, asesoría para la comunicación, entrenamiento para voceros, talleres de sensibilización, revisión de los instrumentos legales laborales, entre otros.</span> 
      </div>
    </div>
  </div>

  {/* TALLERES */}
  <div id="talleres1" className="talleres ai-center flex jc-center m w100">
    <div className="capa1 inline-v z10">
      <h2 className="mB03 _desk c">TALLERES DE EMPLEABILIDAD <br/> PARA EMPRESAS </h2>
      <h2 className="mB03 _mobile c">TALLERES <br/> DE EMPLEABILIDAD <br/> PARA EMPRESAS </h2>
      <div className="tx2 mb3">
        <span>Preparamos y ejecutamos TALLERES DE EMPLEABILIDAD GRUPALES para empresas en procesos de retiro o desvinculación laboral o también para áreas de empleabilidad de Instituciones Educativas. Estos talleres se desarrollan en 4 horas / 6 horas u 8 horas.</span>
        <span>Tiene un enfoque principal respecto del proceso de transición de carrera (recolocación laboral) y otro desde el emprendimiento. A partir de la innovación metodológica lograda con la investigación en el campo de la transición de carrera de los últimos 5 años, podemos clarificar el proceso y capacitar/entrenar en todos los aspectos relevantes del mismo, usando las estrategias, modelos, herramientas y métodos mas prestigiosos para alcanzar los resultados pertinentes.</span>
      </div>
    </div>    
    <div style={{ zIndex: 100 }} className="talleres-gallery">
      { state.showCarrousel &&
        <div className="carousel-s1">
          <Carousel plugins={['arrows']}
            onChange={this.changeCarrousel}
            value={state.carruselValue}
            style={{ maxWidth: '50vw', height: '80%' }}>
            <div className="card w100">
              <img src="images/talleres2.jpeg" alt="foto de talleres"/>
            </div>
            <div className="card w100">
              <img src="images/talleres2.jpeg" alt="foto de talleres"/>
            </div> 
            <div className="card w100">
              <img src="images/talleres3.jpeg" alt="foto de talleres"/>
            </div>
          </Carousel>   
          <Dots value={state.carruselValue} onChange={this.changeCarrousel} number={3} />
        </div>   
      }
    </div>    
    <img className="hide" src="images/empleabilidad3.png"/>   
    <ImageSVG svgRaw={esquina6_svg} alt="" className="esquina4"/>
  </div>
  {/* SLIDER DE TALLERES */}
  <div id="talleres1" className="talleres2 inline-v jc-center hide">
    <ImageSVG svgRaw={esquina5_svg} alt="" className="esquina5"/>
    <span className="title12">NUESTROS TALLERES</span>
    {/*  Fotos de talleres (provisional) */}
    <span className="text11">Fotos de algunos talleres realizados.</span>
    <div className="fotos1 inline jc-center z10">
      <img src="images/talleres1.jpeg" alt=""/>
      <img src="images/talleres2.jpeg" alt=""/>
      <img src="images/talleres3.jpeg" alt=""/>
    </div>
    {/* Slider de Talleres */}
    <div className="talleres4 hide">
      <div className="talleres5 s1 glide">
        <div className="glide__track w100" data-glide-el="track">
          <ul id="li-publicaciones" className="glide__slides w100">
            <li>
              <div className="card1">
                <div>
                  <div className="tt">Nombre de Taller 1</div>
                  <img src="images/talleres_1.jpg" alt="talleres"/>
                </div>
                <div className="tt1 inline-v">
                  <span>Lofficiis cupiditate aut enim totam consequuntur quas consectetur pariatur tenetur nisi expedita incidunt iusto vitae accusamus nobis?</span>
                  <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Placeat tempore ducimus inventore at?</span>
                </div>                
              </div>
            </li>
            <li>
              <div className="card1">
                <div>
                  <div className="tt">Nombre de Taller 1</div>
                  <img src="images/talleres_1.jpg" alt="talleres"/>
                </div>
                <div className="tt1 inline-v">
                  <span>Lofficiis cupiditate aut enim totam consequuntur quas consectetur pariatur tenetur nisi expedita incidunt iusto vitae accusamus nobis?</span>
                  <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Placeat tempore ducimus inventore at?</span>
                </div>                
              </div>
            </li>
            <li>
              <div className="card1">
                <div>
                  <div className="tt">Nombre de Taller 1</div>
                  <img src="images/talleres_1.jpg" alt="talleres"/>
                </div>
                <div className="tt1 inline-v">
                  <span>Lofficiis cupiditate aut enim totam consequuntur quas consectetur pariatur tenetur nisi expedita incidunt iusto vitae accusamus nobis?</span>
                  <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Placeat tempore ducimus inventore at?</span>
                </div>                
              </div>
            </li>
            <li>
              <div className="card1">
                <div>
                  <div className="tt">Nombre de Taller 1</div>
                  <img src="images/talleres_1.jpg" alt="talleres"/>
                </div>
                <div className="tt1 inline-v">
                  <span>Lofficiis cupiditate aut enim totam consequuntur quas consectetur pariatur tenetur nisi expedita incidunt iusto vitae accusamus nobis?</span>
                  <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Placeat tempore ducimus inventore at?</span>
                </div>                
              </div>
            </li>
            <li>
              <div className="card1">
                <div>
                  <div className="tt">Nombre de Taller 1</div>
                  <img src="images/talleres_1.jpg" alt="talleres"/>
                </div>
                <div className="tt1 inline-v">
                  <span>Lofficiis cupiditate aut enim totam consequuntur quas consectetur pariatur tenetur nisi expedita incidunt iusto vitae accusamus nobis?</span>
                  <span>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Placeat tempore ducimus inventore at?</span>
                </div>                
              </div>
            </li>
          </ul>
        </div>
        <div className="glide__arrows" data-glide-el="controls">
          <button className="glide__arrow glide__arrow--left" data-glide-dir="<">{"<"}</button>
          <button className="glide__arrow glide__arrow--right" data-glide-dir=">">{">"}</button>
        </div>
        <div className="glide__bullets" data-glide-el="controls[nav]">
          <button className="glide__bullet" data-glide-dir="=0"></button>
          <button className="glide__bullet" data-glide-dir="=1"></button>
          <button className="glide__bullet" data-glide-dir="=2"></button>
          <button className="glide__bullet" data-glide-dir="=3"></button>
          <button className="glide__bullet" data-glide-dir="=4"></button>
        </div>
      </div>  
    </div>
  </div>

  {/* RECOLOCACION PARA EMPRESAS */}
  <BgParallax className="_desk empresas" 
    imageSrc="images/consultoria5.jpg" innerCss="inline-h"
  >
    <div>
      <div className="emp1 inline-h ls2">RECOLOCACIÓN PARA EMPRESAS</div>
      <div className="emp2">Asesoramos y elaboramos procesos de recolocación a nivel corporativo. Poseemos programas, recursos y herramientas atractivas para que los trabajadores encuentren un puesto acorde a sus expectativas y en concordancia con los intereses de la empresa. Poseemos vasta experiencia en programas de recolocación.</div>
    </div>
  </BgParallax>
  <div className="m-empresas inline-v _mobile w100"
    style={{ backgroundImage: 'url(images/meeting1.jpg)' }}>
    <div className="ctn4 inline-v">
      <h2>RECOLOCACIÓN PARA <br/> EMPRESAS</h2>
      <div className="tx2 mT02 mB02">
        <span>Asesoramos y elaboramos procesos de recolocación a nivel corporativo. Poseemos programas, recursos y herramientas atractivas para que los trabajadores encuentren un puesto acorde a sus expectativas y en concordancia con los intereses de la empresa. Poseemos vasta experiencia en programas de recolocación.</span>
      </div>
    </div>
  </div>
  <div id="noticias1" className="noticias w100 inline-v"
    style={{ display: 'none' }}>
    <div><h3 className="mB04">NOTICIAS Y PUBLICACIONES</h3>
      </div>
    <div style={{ maxWidth: ' 98vw' }} className="unislider_ctn">
      <div id="slider2" className="inline-h car1 unislider" 
        style={{ marginBottom: 'calc(1vw + 2.5vh)' }}>
          <div className="pub">
              <img src="images/fondo1.jpg" alt=""/>
              <h3>¿Por qué no funciona tu búsqueda de Empleo?</h3>
              <div>
                  <span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis ducimus praesentium fugiat porro magni, debitis quos nemo dicta quidem officiis blanditiis eaque...</span>
              </div>
          </div>
          <div className="pub">
              <img src="images/fondo1.jpg" alt=""/>
              <h3>¿Por qué no funciona tu búsqueda de Empleo?</h3>
              <div>
                  <span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis ducimus praesentium fugiat porro magni, debitis quos nemo dicta quidem officiis blanditiis eaque...</span>
              </div>
          </div>
          <div className="pub">
              <img src="images/fondo1.jpg" alt=""/>
              <h3>¿Por qué no funciona tu búsqueda de Empleo?</h3>
              <div>
                  <span>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Omnis ducimus praesentium fugiat porro magni, debitis quos nemo dicta quidem officiis blanditiis eaque...</span>
              </div>
          </div>
      </div>
    </div>
  </div>
  <ContactoForm/>  
  <div style={{ backgroundImage: "url(images/backoffice3.jpg)" }} 
    className="fondo-r _desk inline-v w100">
      <ImageSVG svgRaw={recolocatefondo5_svg} alt=""/>
  </div>
  <Footer1 />
  </>
  }
}
